// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlGjn1-buuxFQxdp3qvrQh0hNUr5fHSVM',
    appId: '1:302702264777:web:9521335bc5992e1c7ba818',
    messagingSenderId: '302702264777',
    projectId: 'rmnotes',
    authDomain: 'rmnotes.firebaseapp.com',
    storageBucket: 'rmnotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVKksFGqLaWUy5wkZoFxWDlge1V7Tr_FA',
    appId: '1:302702264777:android:9bd0efc7dcd01a8a7ba818',
    messagingSenderId: '302702264777',
    projectId: 'rmnotes',
    storageBucket: 'rmnotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDsUWecniTzI_H4TunvNDR9uPDVAvvwAk',
    appId: '1:302702264777:ios:a3ec8ffdcbabb38a7ba818',
    messagingSenderId: '302702264777',
    projectId: 'rmnotes',
    storageBucket: 'rmnotes.appspot.com',
    iosClientId: '302702264777-46gapf9mgcqh26v7oo8lmkua7r7vq7ht.apps.googleusercontent.com',
    iosBundleId: 'com.rifazsolutions.rmnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDsUWecniTzI_H4TunvNDR9uPDVAvvwAk',
    appId: '1:302702264777:ios:a3ec8ffdcbabb38a7ba818',
    messagingSenderId: '302702264777',
    projectId: 'rmnotes',
    storageBucket: 'rmnotes.appspot.com',
    iosClientId: '302702264777-46gapf9mgcqh26v7oo8lmkua7r7vq7ht.apps.googleusercontent.com',
    iosBundleId: 'com.rifazsolutions.rmnotes',
  );
}
